### ISSUE TITLE
Poorly written library

### ISSUE THREAD

**Issue by markentingh** [tanrax/FFNM#1]
Yet another library used to deface clean HTML structures and confuse developers who should instead be using semantic HTML and small bits of Javascript separated by .html & .js files. Clearly whoever made this nonsense does not care to build web content but instead wishes to divert the attention of web developers from using these clean, well thought-out technologies to using this garbage that can be compared to Angular and React. Please delete this repository.

**Comment by tanrax** [comment]
@markentingh You are not reporting an issue to me, to give your opinion about the present and future of Web development you have other channels like Reddit. The objective of this tool is educational, for the transition from Web Designer to Front-End. If you don't like it, don't use it.
Greetings.

**Comment by markentingh** [comment]
The existence of this project is the issue. You want to teach people that it's okay to mutilate HTML all while teaching them an obscure syntax for some parasitic language that embeds itself into HTML elements? I've been down this road many times in the past 2 decades to try and comprehend the mental gymnastics you do to justify building this project.

**Comment by tanrax** [comment]
I see that you are very angry with the Javascript ecosystem, with the way of adding HTML (which does not mutilate) new attributes to simplify the development (VueJS and Angular are great representatives).
@markentingh I do believe in you, don't delete any of your repositories and don't be afraid to create or share ideas. I'm sure it will be worth the effort.
Greetings

**Comment by stonecharioteer** [comment]
@tanrax please ignore this guy. Open source isn't for what he thinks it is. No one is asking him to use this library or your work.

Interestingly, I loved your offering of docs in multiple languages. I primarily speak English, but I can understand how this would improve accessibility.

Thank you for your work. Do not let one person discourage you.

**Comment by kirubakaran** [comment]
@tanrax Thank you for your work, and sharing openly. Please continue to do so. Remember that most people in the world are kind and appreciative. Don't read too much into what the toxic vocal minority says. We can't prevent the vocal minority from being toxic, but we can learn to ignore them. But it is easier said, than done, I know. Wishing you all the best!

**Comment by tanrax** [comment]
> @tanrax please ignore this guy. Open source isn't for what he thinks it is. No one is asking him to use this library or your work.
> 
> Interestingly, I loved your offering of docs in multiple languages. I primarily speak English, but I can understand how this would improve accessibility.
> 
> Thank you for your work. Do not let one person discourage you.

Thank you for the sweet words! Opensource is definitely for people like you.

**Comment by tanrax** [comment]
@ kirubakaran Thank you! I'll try to always think of that majority who give their best.

**Comment by anne** [comment]
@tanrax ignore the haters. keep coding. there are loads of terrible people on the Internet that will try to tear you down, just ignore them and keep doing what you do.

**Comment by bowlofstew** [comment]
@tanrax Keep going forward here.  Working in the open as I have learned requires thick skin as many will come with anecdotal as opposed to objective evidence.  This is more so for the case of education projects where one is learning something new in the open where others can watch us succeed or fail from the grandstands.  The other thing to note as many people such as you have experienced in this issue will come with many logical fallacies in their claims. 

Example given with a [quasi-prepositional claim](https://www.logicalfallacies.org/propositional-fallacies.html).
```
Clearly whoever made this nonsense does not care to build web content
```
Could someone write a library in any fashion and also care about building web content?  Bingo you guessed it, yes.  There are actually a few of these embedded into that single run on sentence.

If I notice the combination of both logical fallacies and anecdotal evidence in an issue, I am quick to turn down my expectations for real progress being made for an issue as opposed to something letting off steam. 

**Recommendations**:

1.  Close the first issue in your issue tracker with a won't fix tag.
2. Thank the issue submitter kindly as kindness never hurts.  Bonus points awards of no value awarded if you mention that pull requests are accepted though for varying viewpoints that might capture ways you aren't considering a certain problem being tackled.
3.  Move on.

**Comment by ksaj** [comment]
Dude is just being an elitist prick. Ignore him and everything he does. He's not special, but he sure wants to force the idea that he is upon you for some reason. Maybe he's jealous? Maybe his girl/boyfriend dumped him? Maybe the cream in his coffee curdled this morning? I just can't figure out why he chose *this* out of so many other things out there he could get all bent out of shape over. 

Just like Reddit, you can always expect assholes like this to piss on your parade. It makes them feel better when nobody gives a shit what they've been doing.

**Comment by orlando-mendoza** [comment]
Siempre habrá alguien en la vida que te quiera joder. Algunos lo harán de pura gana, lo harán gratis, sin ganar nada. Asi esla vida y la vida sigue. A palabras necias oídos sordos.

**Comment by stefanos82** [comment]
@markentingh TLDR; If you don't like it, don't use it; as simple as that.

Longer reply: I honestly don't understand your toxicity nor your bitterness.

Who the hell gave you the right to condemn someone's dreams or passions to learn new things, by coming here and bombard them with pessimism and negativity?

You know, with constructive criticism you could convince the project creator that your suggestions are correct for these X, Y, and Z reasons **AND** you are willing to mentor this person at all costs, but no; you came here in the issues section to be **the very first ticket** and decided to be the person that burns this person's wings from flying high to live their dreams...

Seriously, what's wrong with you?

**Comment by john-h-k** [comment]
> all while teaching them an obscure syntax for some parasitic language that embeds itself into HTML elements

and you consider JS to not be this?????

**Comment by tanrax** [comment]
Thank you all for your advice and love. In the end the issue has been turned around and is becoming the opposite of being closed, it is gaining stars! The Opensource community is great.

**Comment by sergiotapia** [comment]
true big dick energy lmao

**Comment by markentingh** [comment]
Clearly none of you believe in semantic web development. Let me be perfectly clear as to why this project (among many other projects) are an abomination to the web. HTML is a markup language and SHOULD CONTAIN ABSOLUTELY NO LOGIC WHATSOEVER. In fact, HTML should be easy to read, contain a clean structure that can be easily stylized without the need to add class names everywhere. HTML should never use the style attribute, and should only rarely use data- attributes when it is impossible to store all structured data within text elements or JavaScript. HTML SHOULD BE ELEGANT. PERIOD. NO EXCUSES.

All UI interactions and UI logic should be contained in your CSS file. Any other logic that cannot be engineered using CSS should be written in JavaScript and USED SPARSELY. For web applications, JavaScript should be used to make AJAX calls and handle History API and any other APIs required by the application. 

Under NO circumstances should HTML be used for anything other than defining the structure of your user interface. GOT IT? NOW DELETE THIS PROJECT IF YOU WISH TO SAVE FACE. Otherwise, continue repeating history like all the other fools before you. Okay?

**Comment by markentingh** [comment]
@tanrax I'm not angry with the JavaScript atmosphere. In fact, I do like JavaScript very much. The problem that I have is with people who think it's okay to mutilate HTML. HTML has matured a lot over the past 2 decades. I really don't want new generations of developers to think it's okay to mutilate HTML. I've been hired by many companies in the past who had this problem where their previous development team used JS libraries that mutilated HTML and thus, it was extremely frustrating for me and others to try and write HTML for those projects and even worse, debug those projects when issues arised related to those JS libraries. They are black boxes full of garbage. Do you know how many hundreds of millions of dollars have been lost because companies hired teams of developers to migrate AWAY from Angular-like JS libraries? I'm tired of reading about all these up-and-coming JS libraries that add logic into HTML. I'm here to fight all of this backwards thinking. Shame on all of you for defending this project.

**Comment by ksaj** [comment]
The hero is out to save the world. Give him a biscuit and everyone move on. Wow what a self-righteous asshole.

**Comment by infogulch** [comment]
Walking up to someone else's garden and pissing on their flowers won't convince anyone to want to visit yours.

**Comment by markentingh** [comment]
Call me what you want, but you are all fools. Good luck with your library and ruin of all your HTML.

**Comment by notviri** [comment]
(You)

**Comment by stonecharioteer** [comment]
Really man, not cool.

Why are you so sore? There is a way to teach, and ridicule is not the way.

Let's assume you are right. If you care enough to comment, you could instead spend the time to teach people why with a softer tone. You fight what you consider by example. You seem to run a company, did you suffer a loss because of Angular? Did you lose a lot of money?

You might even be justified in saying that javascript frameworks are the plague. Then be better. Show us how. Teach. Educate.

Instead, you come to shout at a lone developer who just wanted to share a bit of work he did over a weekend. That is not cool.

This is analogous of someone criticizing someone who is painting using different colours, telling them that there is only one way to use a canvas.

There are no "SHOULD"s in software. If there were, no one would have thought connective every computer in the world to each other would be a sane idea.

Frankly, you sound like you need a hug. I hope you get over the soreness.

**Comment by tanrax** [comment]
@markentingh I understand your message, but I don't share the ways. 

However, I want to tell you that some years ago logic and variables were added to CSS. It's crazy idiots!: they are for giving styles. More time ago it would be another madness to use AJAX: Javascript should not be executed asynchronously, it's dangerous! Now the evolution of the HTML allows us to take part of the logic to its structure, we already did it with the Back-End with the template engines! Now Angular and Vue simplify its use, allowing web designers to have more tools. It is not the future, but the present. This syntax is already becoming a standard.

**Comment by tanrax** [comment]
@markentingh I'm with @stonecharioteer , if you want us to be purists and take the path of good... show us (but don't call us idiots). I'd love to read your blog or I'll read your courses.

**Comment by stefanos82** [comment]
> Clearly none of you believe in semantic web development. Let me be perfectly clear as to why this project (among many other projects) are an abomination to the web. HTML is a markup language and SHOULD CONTAIN ABSOLUTELY NO LOGIC WHATSOEVER. In fact, HTML should be easy to read, contain a clean structure that can be easily stylized without the need to add class names everywhere. HTML should never use the style attribute, and should only rarely use data- attributes when it is impossible to store all structured data within text elements or JavaScript. HTML SHOULD BE ELEGANT. PERIOD. NO EXCUSES.
> 
> All UI interactions and UI logic should be contained in your CSS file. Any other logic that cannot be engineered using CSS should be written in JavaScript and USED SPARSELY. For web applications, JavaScript should be used to make AJAX calls and handle History API and any other APIs required by the application.
> 
> Under NO circumstances should HTML be used for anything other than defining the structure of your user interface. GOT IT? NOW DELETE THIS PROJECT IF YOU WISH TO SAVE FACE. Otherwise, continue repeating history like all the other fools before you.
> 
> Shame on all of you for thinking it's okay to not only write JavaScript libraries that deface HTML, but to teach others that it is okay. IT IS ABSOLUTELY NOT OKAY TO DO THIS. SHAME ON ALL OF YOU!

Bloody hell, **THE AUDACITY** of this dude...I'm just speechless!

**Comment by markentingh** [comment]
@stefanos82 THE AUDACITY! I know, right? @ksaj I would agree I am acting self-righteous when I think about it. I've been obsessed with web development since 1998, I have high standards for myself and the rest of the community, I am not outspoken but when I saw this repository featured on HackerNews, I guess I just snapped. Everywhere I look, on Indeed or StackOverflow for employment opportunities, nearly every software engineer position includes required knowledge of ANGULAR. I am in shock that so many people would use such bloated junk-ware that ruins the process of writing elegant HTML. @tanrax, thank you for sympathizing even a little bit with me. @stonecharioteer ridicule is one way of teaching, perhaps not the best way, but maybe I'm just an angry person and this is how I chose to express my concern for this project along with Angular and other similar projects. @sergiotapia I get ya, I'm just fed up with the web dev ecosystem. HTML, in my opinion, is perfect the way it is. We don't need to extend it, and we certainly don't need to teach people that it should be extended outside of engineering web components. Logic within HTML is bad practice, and I would like to see you prove me wrong. It's bad enough we have to use a JIT language on the web, but using a JIT language to JIT compile HTML attribute logic is just plain wrong. Also, the web browser keeps all those attribute strings in memory. It's just bloat, plain and simple. HTML needs to be kept pure, elegant, clean, easy to read, easy to parse, minimal, and plain. 

My final point is this: You could be developing an application or an innovative tool or something that would help the world, but instead, you are building something that hinders the web development community, causes more learning curves, wastes our time and energy (because one day I guarantee this project will fizzle out JUST LIKE Angular 1 AND Angular x.x AND React). At best, this project brought forth concern about the current state of web technology, tech debt, and bad practices.

**Comment by stonecharioteer** [comment]
@markentingh :) see, a calmer tone works better. I hear ya. I see a lot of people who do react, angular and when I ask them to write a simple html table, they flounder. These are the end days I tell you

**Comment by pacuna** [comment]
I would take this guy more seriously if he had done or worked on something interesting. But come on now, you haven't won the right to rant like this yet (and after 18 years you probably never will).

**Comment by markentingh** [comment]
@pacuna https://www.github.com/datasilk sorry for the plug but you asked for it. I have a lot of very interesting projects that I've developed over the past 5 years. https://www.datasilk.io

**Comment by codymikol** [comment]
🍿
